#!/bin/bash
set -eu

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

CDK_VERSION=$(cat CDK_VERSION)

docker build --build-arg CDK_VERSION=${CDK_VERSION} ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .
